[workspace]
members = [
"diesel_derives_extra",
"diesel_derives_traits"
]

[patch.crates-io]
"diesel_derives_extra" = { path = "diesel_derives_extra" }
"diesel_derives_traits" = { path = "diesel_derives_traits" }
